bugfix: encryption/decryption
needmoney90/merkato pull request #209
Opened 2018-06-16 19:54 UTC by nasaWelder

2018-06-16 23:24 UTC, mark-antony1 requested changes

2018-06-16 23:24 UTC, mark-antony1 commented on merkato/merkato_config.py
> +    if isinstance(password, str):
extract this to a util function

2018-06-16 23:24 UTC, mark-antony1 commented on merkato/merkato_config.py
> +    if isinstance(password, str):
*all of the if statements

2018-06-16 23:24 UTC, mark-antony1 commented on merkato/merkato_config.py
> +def decrypt_merkato(config, password=None):
this seems mostly copy and pasted from decrypt_keys? Instead of supply the whole object, just supply the exchange config to decrypt keys. decrypt keys will mutate the config passed to it.

2018-06-17 04:48 UTC, nasaWelder commented on merkato/merkato_config.py
> +    if isinstance(password, str):
I don't like extracting stuff to other places, makes debugging a nightmare. We're still debugging way too much to be jumping across 5 files to trace a type issue.

2018-06-17 04:49 UTC, nasaWelder commented on merkato/merkato_config.py
> +def decrypt_merkato(config, password=None):
This is me doing that, then extracting it to here.

2018-06-17 20:06 UTC, 15chrjef commented on merkato/merkato_config.py
> +    if isinstance(password, str):
I strongly disagree. Each function should be as small as possible, take as few arguments as possible and only do what would be expected from the function name. 

If the above is done properly, then function extraction is a must. This strategy makes things much more easy to read. This is best so you can see the stack trace of functions that describe their logic and literally read in English what was supposed to happen vs what did.

2018-06-17 20:07 UTC, 15chrjef commented on merkato/merkato_config.py
> +def decrypt_merkato(config, password=None):
The point is that decrypt merkato is duplicate code. The config for ONLY the exchange could be passed to decrypt_keys and accomplish the same result.

2018-06-17 20:34 UTC, nasaWelder commented on merkato/merkato_config.py
> +def decrypt_merkato(config, password=None):
You're right, I'm still getting used to the utility function thing editing stuff in place. I normally use object attributes, different way of thinking I guess

2018-06-21 05:09 UTC, livinginformation commented
Is this mergeable, @nasaWelder? Has a small conflict, but doesn't look like much

2018-06-21 05:11 UTC, nasaWelder commented
Just need to delete my change in that conflict

2018-06-21 17:40 UTC, nasaWelder commented
@livinginformation should be good

2018-06-21 17:46 UTC, livinginformation commented
@15chrjef waiting on an approve before merging

2018-06-21 18:12 UTC, nasaWelder commented
added profit margin

2018-06-21 20:55 UTC, 15chrjef commented
Hey @nasaWelder what here is still needed to be merged? Master is currently implemented in such a way that encryption and decryption work on simple_app

2018-06-21 22:39 UTC, nasaWelder commented
Didn't work for me unless I added the bytes stuff. Also there's profit margin added to the GUI.

2018-06-22 17:09 UTC, nasaWelder commented
Why isn't this merged yet?

2018-06-22 17:16 UTC, livinginformation commented
@15chrjef is this mergeable?

2018-06-22 19:17 UTC, 15chrjef commented
There dosent seem to be a bytes issue on windows or OSX, can you pull from master and try again? 

My feeling is the profit margin is good, and the encryption is probably unneeded, renaming the pr and/or commit messages would help clarify.

2018-06-23 01:01 UTC, mark-antony1 approved these changes

2018-06-23 02:07 UTC, merged